export const CATEGORIES = [
  'Services',
  'Tools',
  'Electronics',
  'Furniture',
  'Outdoor/Sports',
  'Vehicles',
  'Kids/Baby',
  'Home/Garden',
  'Farm/Garden',
  'Tickets/Events',
  'Other',
];

export const CONDITIONS = ['New', 'Like New', 'Good', 'Fair'];

export const CITIES = ['Bentonville', 'Rogers', 'Springdale', 'Fayetteville', 'Other'];

export const SERVICE_CATEGORIES = ['Services'];

export const MOCK_USER = {
  id: 'user-1',
  name: 'Ben Williams',
  email: 'bwbuse@gmail.com',
  city: 'Bentonville',
  zip: '72712',
  completedTrades: 3,
};

export const MOCK_LISTINGS = [
  {
    id: 'listing-1',
    title: 'Weekly Lawn Mowing Service',
    description: `Professional lawn mowing service available weekly or bi-weekly. I have all my own equipment -- mower, edger, blower. Serving Bentonville and surrounding areas. I take pride in a clean, manicured lawn. Happy to do seasonal cleanups too. Reliable, on time, and neighborly.`,
    category: 'Services',
    condition: null,
    iHave: 'Lawn mowing service (weekly or bi-weekly)',
    iWant: ['Outdoor/Sports'],
    iWantText: 'Fishing kayak or paddleboard',
    city: 'Bentonville',
    zip: '72712',
    openToOffers: true,
    views: 142,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
    photo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    poster: {
      id: 'user-2',
      name: 'Marcus Dale',
      city: 'Bentonville',
      zip: '72712',
      completedTrades: 7,
    },
  },
  {
    id: 'listing-2',
    title: 'Standing Desk - Adjustable Height',
    description: `Motorized sit/stand desk, 60 inches wide. Works perfectly. Downsizing my home office and this beast needs a new home. Electric height adjustment, memory presets for 3 heights. Solid steel frame, bamboo top. Only minor scratches on the base from moving. Pick up in Rogers.`,
    category: 'Furniture',
    condition: 'Good',
    iHave: 'Motorized standing desk (60 inch, bamboo top)',
    iWant: ['Outdoor/Sports'],
    iWantText: 'Road bike or mountain bike',
    city: 'Rogers',
    zip: '72756',
    openToOffers: false,
    views: 89,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    photo: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80',
    poster: {
      id: 'user-3',
      name: 'Sarah Chen',
      city: 'Rogers',
      zip: '72756',
      completedTrades: 4,
    },
  },
  {
    id: 'listing-3',
    title: 'Guitar Lessons (All Levels)',
    description: `I have been playing for 20 years and teaching for 10. I teach acoustic and electric, beginner through intermediate. Can teach at your home or mine in Fayetteville. I do 30 or 60 minute lessons, weekly or bi-weekly. Great for kids or adults. Patient, fun, structured approach.`,
    category: 'Services',
    condition: null,
    iHave: 'Guitar lessons (30 or 60 min, any level)',
    iWant: ['Electronics'],
    iWantText: 'Camera body or lens (mirrorless or DSLR)',
    city: 'Fayetteville',
    zip: '72701',
    openToOffers: true,
    views: 211,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 29 * 24 * 60 * 60 * 1000).toISOString(),
    photo: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=600&q=80',
    poster: {
      id: 'user-4',
      name: 'Jake Morrison',
      city: 'Fayetteville',
      zip: '72701',
      completedTrades: 12,
    },
  },
  {
    id: 'listing-4',
    title: 'Farm Fresh Eggs + Backyard Chickens',
    description: `We have 18 hens producing more eggs than we can use -- about 10 dozen a week. Happy to do a recurring trade. We also have 4 pullets (young hens) available if you want to start your own flock. All raised on pasture and fed non-GMO feed. Springdale area pickup.`,
    category: 'Farm/Garden',
    condition: 'New',
    iHave: 'Farm fresh eggs (ongoing) + backyard pullets',
    iWant: ['Farm/Garden', 'Tools'],
    iWantText: 'Garden seeds, seedlings, or tools',
    city: 'Springdale',
    zip: '72764',
    openToOffers: true,
    views: 318,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    photo: 'https://images.unsplash.com/photo-1518492104633-130d0cc84637?w=600&q=80',
    poster: {
      id: 'user-5',
      name: 'Linda Farmer',
      city: 'Springdale',
      zip: '72764',
      completedTrades: 9,
    },
  },
  {
    id: 'listing-5',
    title: 'Razorbacks Season Tickets (2 seats)',
    description: `Two club-level seats for the upcoming Razorbacks football season. Section 123, Row 12, excellent sightlines. I travel too much for work this year to use them. These are transferable. Face value is significant -- looking for something of equal value or a creative trade. Go Hogs!`,
    category: 'Tickets/Events',
    condition: 'New',
    iHave: 'Razorbacks football season tickets (2 club seats)',
    iWant: ['Vehicles', 'Outdoor/Sports', 'Other'],
    iWantText: 'RV, camper, or outdoor recreation equipment',
    city: 'Fayetteville',
    zip: '72701',
    openToOffers: true,
    views: 503,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    photo: 'https://images.unsplash.com/photo-1567459169668-5f3f4fd0c7e1?w=600&q=80',
    poster: {
      id: 'user-6',
      name: 'Todd Harrington',
      city: 'Fayetteville',
      zip: '72703',
      completedTrades: 2,
    },
  },
  {
    id: 'listing-6',
    title: 'DeWalt Power Drill Set (10-piece)',
    description: `DeWalt 20V MAX 10-piece power tool combo set. Includes drill/driver, circular saw, jigsaw, reciprocating saw, angle grinder, oscillating tool, and more. Two batteries, fast charger, and carrying bag. All tools work great. Upgrading to Festool for my shop.`,
    category: 'Tools',
    condition: 'Good',
    iHave: 'DeWalt 20V MAX 10-piece power tool set',
    iWant: ['Tools'],
    iWantText: 'Pressure washer (2000 PSI+)',
    city: 'Bentonville',
    zip: '72712',
    openToOffers: false,
    views: 176,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 26 * 24 * 60 * 60 * 1000).toISOString(),
    photo: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&q=80',
    poster: {
      id: 'user-7',
      name: 'Ryan Tate',
      city: 'Bentonville',
      zip: '72712',
      completedTrades: 5,
    },
  },
  {
    id: 'listing-7',
    title: "Kids 20-inch Bike + Helmet (ages 6-9)",
    description: `Huffy 20-inch kids bike in great shape -- purple with white accents. Matching Bell helmet included. My daughter outgrew it after one summer. Hand brakes, kickstand, training wheels still in the box. Helmet is barely used and fits head sizes 50-57cm. Perfect for a kid just learning.`,
    category: 'Kids/Baby',
    condition: 'Like New',
    iHave: "Kids 20-inch bike + helmet (ages 6-9)",
    iWant: ['Kids/Baby', 'Outdoor/Sports'],
    iWantText: 'Trampoline or outdoor play equipment',
    city: 'Rogers',
    zip: '72758',
    openToOffers: true,
    views: 94,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 23 * 24 * 60 * 60 * 1000).toISOString(),
    photo: 'https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=600&q=80',
    poster: {
      id: 'user-8',
      name: 'Amy Lester',
      city: 'Rogers',
      zip: '72758',
      completedTrades: 6,
    },
  },
  {
    id: 'listing-8',
    title: 'Web Design & Development Services',
    description: `Full-stack web developer with 8 years experience. I build fast, beautiful websites and web apps. Small business sites, landing pages, e-commerce, custom web apps. Happy to do ongoing support. Offering a 5-page business site in trade. References available from local Bentonville clients.`,
    category: 'Services',
    condition: null,
    iHave: 'Web design & dev (5-page business site)',
    iWant: ['Services'],
    iWantText: 'Accounting, bookkeeping, or legal services',
    city: 'Bentonville',
    zip: '72712',
    openToOffers: true,
    views: 287,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    photo: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=600&q=80',
    poster: {
      id: 'user-9',
      name: 'Chris Park',
      city: 'Bentonville',
      zip: '72712',
      completedTrades: 15,
    },
  },
  {
    id: 'listing-9',
    title: 'Sectional Sofa (gray, 3-piece)',
    description: `West Elm-style sectional, light gray performance fabric. 3 pieces that can be configured multiple ways. Very comfortable, holds up great with kids and dogs. Moving to a smaller place so I cannot keep it. One small stain on the corner piece (barely visible). Must arrange your own pickup -- it is big.`,
    category: 'Furniture',
    condition: 'Good',
    iHave: '3-piece gray sectional sofa',
    iWant: ['Furniture', 'Home/Garden'],
    iWantText: 'Patio furniture set or outdoor dining set',
    city: 'Fayetteville',
    zip: '72701',
    openToOffers: false,
    views: 131,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000).toISOString(),
    photo: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80',
    poster: {
      id: 'user-10',
      name: 'Megan Ross',
      city: 'Fayetteville',
      zip: '72701',
      completedTrades: 3,
    },
  },
  {
    id: 'listing-10',
    title: 'Perception Kayak (10ft, sit-inside)',
    description: `Perception Tribe 9.5 sit-inside kayak in excellent condition. Great for Lake Leatherwood, Beaver Lake, or the Illinois River. Paddle included. Had it two summers and it has been well-cared-for. Needs a car with roof rack or a truck bed. Comes with carry handles and drain plug.`,
    category: 'Outdoor/Sports',
    condition: 'Like New',
    iHave: 'Perception kayak (9.5ft) + paddle',
    iWant: ['Outdoor/Sports'],
    iWantText: 'Golf clubs (full set preferred)',
    city: 'Rogers',
    zip: '72756',
    openToOffers: true,
    views: 224,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
    photo: 'https://images.unsplash.com/photo-1544551763-92ab472cad5d?w=600&q=80',
    poster: {
      id: 'user-11',
      name: 'Dan Fischer',
      city: 'Rogers',
      zip: '72756',
      completedTrades: 8,
    },
  },
  {
    id: 'listing-11',
    title: '2015 Toyota Tacoma (TRD Sport)',
    description: `Clean 2015 Tacoma TRD Sport, 4x4, 6-speed manual. 98k miles. Always maintained, no accidents. New tires and brakes last year. This truck is a beast -- great for Ozark trails and Walmart runs alike. Looking for a creative trade, willing to consider partial cash + trade combos.`,
    category: 'Vehicles',
    condition: 'Good',
    iHave: '2015 Toyota Tacoma TRD Sport 4x4 (98k mi)',
    iWant: ['Vehicles', 'Other'],
    iWantText: 'Truck camper shell, RV, or boat + trailer',
    city: 'Bentonville',
    zip: '72712',
    openToOffers: true,
    views: 612,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 29 * 24 * 60 * 60 * 1000).toISOString(),
    photo: 'https://images.unsplash.com/photo-1589750602846-60028879da69?w=600&q=80',
    poster: {
      id: 'user-12',
      name: 'Kevin Stout',
      city: 'Bentonville',
      zip: '72712',
      completedTrades: 1,
    },
  },
  {
    id: 'listing-12',
    title: 'Sewing & Alterations Service',
    description: `Professional seamstress with 15+ years of experience. I do clothing alterations, repairs, custom sewing, and quilting. Hemming, taking in or letting out, zipper replacements, patches. I can also make custom curtains, pillowcases, and tote bags. Springdale-based, pick-up and drop-off available.`,
    category: 'Services',
    condition: null,
    iHave: 'Sewing, alterations & custom sewing services',
    iWant: ['Home/Garden', 'Farm/Garden'],
    iWantText: 'Fabric (cotton or quilting), sewing machine, or garden plants',
    city: 'Springdale',
    zip: '72764',
    openToOffers: true,
    views: 78,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    photo: 'https://images.unsplash.com/photo-1605289982774-9a6fef564df8?w=600&q=80',
    poster: {
      id: 'user-13',
      name: 'Rosa Mendez',
      city: 'Springdale',
      zip: '72764',
      completedTrades: 11,
    },
  },
];

export const MOCK_CONVERSATIONS = [
  {
    id: 'conv-1',
    listingId: 'listing-6',
    listing: null, // will be resolved at runtime
    otherUser: {
      id: 'user-7',
      name: 'Ryan Tate',
      city: 'Bentonville',
      zip: '72712',
      completedTrades: 5,
    },
    messages: [
      {
        id: 'msg-1',
        senderId: 'user-7',
        text: 'Hey! I saw your proposal for the DeWalt set. I love what you are offering. What kind of lawn mowing schedule were you thinking?',
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'msg-2',
        senderId: 'user-1',
        text: 'Hi Ryan! I was thinking once a week through the summer, maybe bi-weekly in fall. About an hour per visit for a typical yard. Does that sound fair?',
        timestamp: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'msg-3',
        senderId: 'user-7',
        text: 'That sounds great. My yard is about 1/4 acre, fenced backyard. When could you come by to look at it?',
        timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      },
    ],
    unread: true,
    lastMessageAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'conv-2',
    listingId: 'listing-3',
    listing: null,
    otherUser: {
      id: 'user-4',
      name: 'Jake Morrison',
      city: 'Fayetteville',
      zip: '72701',
      completedTrades: 12,
    },
    messages: [
      {
        id: 'msg-4',
        senderId: 'user-1',
        text: 'Jake -- I would love to trade guitar lessons for some web design help. I am building a site for my teaching studio. Interested?',
        timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'msg-5',
        senderId: 'user-4',
        text: 'That is awesome, yes! I have been wanting a proper site. How many lessons would we be talking for a 5-page site?',
        timestamp: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
      },
    ],
    unread: false,
    lastMessageAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
  },
];

// Attach listing objects post-init
MOCK_CONVERSATIONS[0].listing = MOCK_LISTINGS[5];
MOCK_CONVERSATIONS[1].listing = MOCK_LISTINGS[2];

export const TRADE_TEMPLATES = {
  Services: 'Hi! I saw your listing and I am interested in a trade. I can offer [describe your service] in exchange. I would love to discuss what works for both of us.',
  Tools: 'Hey! I have [tool/item] in great condition that I would love to trade for what you are offering. Happy to send photos or meet up to check things out first.',
  Electronics: 'Hi! I am interested in trading for your listing. I have [item] that I think would be a fair exchange. Want to discuss details?',
  Furniture: 'Hello! I have [furniture item] available that I would like to offer in trade. It is in [condition] condition and available for pickup. Interested?',
  'Outdoor/Sports': 'Hey! Saw your listing -- I have [item] that might interest you. Both are outdoor gear so it feels like a natural fit. Want to chat?',
  Vehicles: 'Hi! I am very interested in your vehicle listing. I have [offer] and would love to discuss a trade. Happy to meet in a public spot to look things over.',
  'Kids/Baby': 'Hi! I have [kids item] in great shape that might work as a trade. My kids have outgrown it and it is just sitting in the garage. Interested?',
  'Home/Garden': 'Hello! I have [item] that I think would be a great trade for what you are offering. It is in [condition] condition and ready to go.',
  'Farm/Garden': 'Hey neighbor! I am interested in trading. I have [produce/plants/tools] available. Would love to keep things local and work something out!',
  'Tickets/Events': 'Hi! I have [tickets/event passes] available that I would like to trade. They are for [event] on [date]. Want to discuss?',
  Other: 'Hi! I am interested in your listing. I have [offer] that I would love to trade. Let me know if you would like to discuss details!',
};
